### ISSUE TITLE
checklist for release

### ISSUE THREAD

**Issue by iqbal-lab** [iqbal-lab-org/viridian_workflow#23]
- [x] Auto-detection of primer scheme from V3, V4, midnight, outputting annotated bam
- [x] tests thereof
- [x] Creation of sorted bam
- [x] Pass to viridian
- [x] JSON block of high-level stats (defined below)
- [x] General robustness improvements 
      - [ ] not try global alignment if too many amplicons dropped (eg >10 by default?)
      - [ ] don't bother with viridian if the workflow spots >N amplicons dropped (N such that total length of genome recovered <90%?)
- [x] Outputting software version in final JSON?

Phil's proposed JSON block for QC
{
'sequencing_quality':{
'primer_based_amplification':<bool>,
'detected_primer_set':<str>,
'total_number_reads': <integer>,<<<<<<< lets make this the reads in the input fastq
'average_read_depth': <float>,    <<<<<<< this is a stupid statistic. shall we take total good reads* length/genome length?
'number_amplicons_dropped': <int>,
'prop_coverage_greater_min_depth_threshold': <float>,
'min_depth_threshold': <int>,
  }
}

I'm a bit confused about what the "sections"/blocks of the final output json are. Can someone add here?

Things being left out of this release

- coverage on SNP alleles in VCF (right @martinghunt ?)
- masking and self-QC incl FRS

**Comment by iqbal-lab** [comment]
**Questions**
 - if someone passes in a primer scheme manually, do we check if it is == one of our inbuilt ones?
 - what if the amplicons and primers are the same as our internally stored V4 (say), but they call it something else?
 - if a user passes in a primer scheme manually, they just pass in a JSON file which presumably includes the name of the scheme as a tag, and we run primer-detection, and we think the best scheme is not the one they pass in, we error out, right? Which is fine. What if we agree their scheme is the best, but they have wrongly named their scheme, to be the same name as one of ours?

**Comment by bede** [comment]
> if someone passes in a primer scheme manually, do we check if it is == one of our inbuilt ones?

Perhaps test for equality of bed records, ignoring name and reverting to ?

> Phil's proposed JSON block for QC

Interested to learn more about what has been proposed, will ask Phil.

Maybe there should be a `notices` field to contain strings explaining certain behaviours e.g. `supplied primer scheme matches built-in scheme`? Else give every corner case its own field.

Another question, how would genome length be calculated?

**Comment by iqbal-lab** [comment]
I think genome length == length of ref.
But I also think it doesn't matter,  average depth is a useless statistic given how depth varies across amplicons. Just including it so we don't keep getting asked for it.

**Comment by iqbal-lab** [comment]
closing this, we made release 0.3.0.
Self-QC deferred to next release
